### PR TITLE
解决github.com/google/martian/log导入异常

### PR DESCRIPTION
**Pull request by QuQu0**
go mod tidy时会报错，用github.com/google/martian/v3/log替代github.com/google/martian/log

### CODE REVIEW

**Comment by rencalo770** [comment]
感谢您提交的pull request.
你当前所使用的golang版本是多少？ 我们使用的版本是go1.14.x
-----------english---------------------
thanks for your pull request! 
which is the version  of golang you use？we use the version of golang is go1.14.x

**Comment by QuQu0** [comment]
It's go1.15 darwin/amd64

**Comment by rencalo770** [comment]
感谢您的回复！
我找了一台干净的mac OS电脑，使用go1.15.6测试了一下，发现下载依赖包是正常的。具体如下：

image

之前我在其他工程(不是gengine)有遇到包下载不下来的情况，然后我删除了一下golang缓存下载的依赖包文件夹，然后重新执行tidy命令就行了。缓存文件夹一般在path/to/go/pkg的某个目录下。
----------------------------------------------------------------
thanks for your reply!
I get a clean MAC OS computer, use the version go1.15 to test to download dependence package, and find it ok. just as follow:
企业微信截图_d236f8bf-be1a-45b2-88c9-360136db9323

In early time, i meet the same problem in other project (not gengine)  as you meet now, Then I deleted the cache dir that golang use to cache the downloaded dependence packages, I run go mod tidy again, and solved the problem. Commonly, the cache dir in some dir in the path "../your/gopath/to/go/pkg/...".

**Comment by QuQu0** [comment]
好的，谢谢解答！

**Pull request closed without merging**
